# TestCompile.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020-2022  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: TestCompile
on: 
  workflow_dispatch: # To run it manually
    description: 'manual build check'
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**TestCompile.yml'
jobs:
  build:
    name: Test compiling examples for Uno
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

#      - name: Checkout custom library
#        uses: actions/checkout@master
#        with:
#          repository: ArminJo/NeoPatterns
#          ref: master
#          path: CustomNeoPatterns # must contain string "Custom"

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
#          required-libraries: Adafruit NeoPixel,PlayRtttl,SoftI2CMaster
          required-libraries: Adafruit NeoPixel,PlayRtttl,NeoPatterns
#          build-properties: -DSERIAL_RX_BUFFER_SIZE=8
